name: Trigger auto deployment for 'techlab-dapr-backend'

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'techlab-dapr-backend/**'
    - '.github/workflows/techlab-dapr-backend.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: sieben.azurecr.io
          username: ${{ secrets.TECHLABCONTAINERAPP_REGISTRY_USERNAME }}
          password: ${{ secrets.TECHLABCONTAINERAPP_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: | 
            sieben.azurecr.io/techlab-dapr-backend:${{ github.sha }}
            sieben.azurecr.io/techlab-dapr-backend:latest
          file: techlab-dapr-backend/Dockerfile          


  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: build
    
  #   steps:
  #     - name: Azure Login
  #       uses: azure/login@v1
  #       with:
  #         creds: ${{ secrets.TECHLABCONTAINERAPP_AZURE_CREDENTIALS }}


  #     - name: Deploy to containerapp
  #       uses: azure/CLI@v1
  #       with:
  #         inlineScript: |
  #           az config set extension.use_dynamic_install=yes_without_prompt
  #           az containerapp registry set -n techlab-dapr-backend -g techlab-container-app --server sieben.azurecr.io --username  ${{ secrets.TECHLABCONTAINERAPP_REGISTRY_USERNAME }} --password ${{ secrets.TECHLABCONTAINERAPP_REGISTRY_PASSWORD }}
  #           az containerapp update -n techlab-dapr-backend -g techlab-container-app --image sieben.azurecr.io/techlab-dapr-backend:${{ github.sha }}
